version: '3'
services:
  eventshuttle-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: eventshuttle-db
    #   # Make database persistent
    #volumes:
    #  - db:/var/lib/postgresql/data
    environment:
      POSTGRES_ROOT_PASSWORD: password
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
    ports:
      - ${POSTGRES_PORT}:5432