---
apiVersion: v1
kind: Service
metadata:
  name: eventshuttle
  namespace: eventshuttle
  labels:
    app: eventshuttle
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: eventshuttle
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventshuttle
  namespace: eventshuttle
  labels:
    app: eventshuttle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventshuttle
  template:
    metadata:
      labels:
        app: eventshuttle
    spec:
      containers:
      - name: eventshuttle
        image: localhost/eventshuttle:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
            protocol: TCP
        readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: 100Mi
              cpu: 5m
            limits:
              memory: 150Mi
              cpu: 15m
        envFrom:
          - configMapRef:
              name: eventshuttle-config
          - secretRef:
              name: eventshuttle-secrets